### PR TITLE
closes #6 ignore case commands

### LINKED ISSUE #6: Ignore case on commands
* Typing "Wog help" will not work for exemple

### PR DESCRIPTION
**Pull request by golngaz**

### CODE REVIEW

File: src/Command/CommandFactory.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export default class CommandFactory {
     }
 
     static handle(message: Message|PartialMessage, di: Di): void {
-        let args = message.content.split(' ');
+        let args = message.content.toLowerCase().split(' ');
```
Comment (vincent4vx) [inline src/Command/CommandFactory.ts]: Do not change case here

File: src/Command/CommandFactory.ts [hunk 2]
```diff
@@ -39,7 +39,7 @@ export default class CommandFactory {
...
 
         if (args.shift() === 'wog') {
```
Comment (vincent4vx) [inline src/Command/CommandFactory.ts]: check with lower case here

**Review by vincent4vx — CHANGES_REQUESTED** [review]

**Review by vincent4vx — APPROVED** [review]
